[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "50b126c9a9eef713e1d61aec96bb129904e31f6b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2cc2650abfade52c31339172ee5aa6c968d389833422e37e1a3d1d0fdd1d1c40"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "3ec87b5d11f620925eaab72741761809a7942605"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "c6fa1ba51b2669853bad1e307bd788abc8ed622aec627652dca60fb4416c79f2"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "68fdd8ffd7da534c0485b7c8289e56965852e6d3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "ea3096dbdc2817eec3047da1b4bbb44ef88e7a642e38374f1167734ef0d87706"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "fc046e406229cde1416d164e8ecc35babb215859"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "505efd8e5782ad0a5c0520bc090527358f08e0df5018c48e843873153e3e72b1"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "d72f033a2b3aff0f1c9e9d5886f45fc294d27d16"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "18dfca98a3df6bfedeb18283290990747be3b6653dadb3099599fcbc1bc67fea"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "8015cf3c0411b03c58b38a63926d13288959e8a2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "f635664e16ea2c54f107d5cb42bda8ca03d5ca08b6cec28ec2c29d462b0e0a92"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56c807c24b050b8c0de4282b39f31db6ca9b351c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "b5a21fe72c56d1057456d6d4b75b8a253612ab1dfdaff4da103b5d42343a2be2"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e070b4d93ebbbcda42028cadc46e35a15e2e781"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "97612721f30ea8e1d087b3f04dad2431b890b15c798946514ee63b6a36b4f9c5"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0fe7ab81db5ff15b37c86365628a4d58ab81781"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "bb9ef5ff3da35b315dd5d682cf35446afbd8f519e77cf6d42bc0ce363932c597"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9556601d9b2e07a56101f9cd3674b4b8ac3f05ee"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "e6d88ea320dab0c4647c0c39a277124080f815616b2c3d380e6664c85fdf5f5a"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df84d55bdcd07857bb5304f4e240bbc590aeba3c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "f9f8e9e8d4feac298659943ab1f73ce374212322fc7f79f724550a9b02be3b7b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f04ae5d03814f18c8ec5adb44f8950952a3dc5cf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "6f6f82499736a9081d6836ded8fcd7197bb1d93af7e9110738022dc39db9843d"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e891565c9e1b93202629f06658298320a46c3ad1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "a7de18c368bf61ded89d63948b2355c4aebdbcfbb1172188d6dda098d0ab3c8e"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f7919e121878c3c75fbfe63183c53294e769bb0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "1db6928e5f0856ab4247380f873902a421ee5fbf615f795367747832484cd8cc"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4599edab2c09aed04d91ad771a9ec2df46bf4dc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "11fc655179b697e9d53eacc9da29c7e92b3f673afef54263c10fa55938e44cdd"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b34f9f204e9c8759d78d305d4da1e4cfbaa37748"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3ae213ec43133935185085acbabfb08745ac2c93e58b86b6cd01deb9018db4dc"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "46c86ee0288f516eda6af2a846abb0c76f8a45bf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "85a67b851ce1d2646138a13afff13754b10ffd96017e71c7782009b9b2c43980"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e6a8d37a8794690f18d697b5017c873f1ccfaaf3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "1d7e55f6060bc7d284c73230a297e1e8286705d345f2dbb7c57ff5e008f400e3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "8a245bab6592118b97c81637d872fc15040f5f70"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "77cf111013af21b72b52a27d95a54b31a21281c6f38f49aa75cb041406c2ec78"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "265c23f61849f8d649e006f748e875124a3c1429"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "81a171e954c0312ab07e15bdfcbd4877da4d3ad4ceb8dd9731573ba780eb566f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "262b915cfb390309e7c2e0515860780de63b128a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "0c9831b390b79fbabf90f458e6c4c7cbbde1d672ff4e8859fb6fdcabbe933b7f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "a45cb54d9cf797e621da752d9f1c9e6cde4cb7ef"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "31742e87af823c10b93e0e16c8cc7c2df7291f66b99e5e5e37082f616c82ff1f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "fbb4828b9b4398c581ddbaa34b7637138fe5eb7f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "71250064076a610c0b26e381239a1fc79f23d1d2afb59e4eec54b9a314eb8110"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "9875b9d62b778bc200cffb44eab14d11302c35d2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3685bbb508f6620f87a1f9c129d9b35b629ad4f9da37ea32382eb3b155526d84"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "0dd351bd2ad628366d815852887071d0b028cfaf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "22f08663164f89c5cdffd6c46ba000ee3ee4bff9948e57b925aa35df6705061d"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "afa80ad99e17cf925f41d35b98e6bb3a839cfe06"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2eed67ecc3657185959dc0810c6f95c8944c53dd9306e48c22f3c2a21cea9900"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "7a62e408851c50d182a41950bd67cbc6875148d2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "a6b82925b66dd49cb2a1594774075a0e2ab6f0c4db445857b1241bda292bc24c"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "045a2c7fb6587aa0bc66e7355632932f16932551"
libgfortran_version = "3.0.0"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "8d8871f33ddd0675362572ca23bf4959a5ad1422379c520d39d0c831fdea6fc9"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "a8ac027e613a13babc6927bf6aa5c2e85a2c10d1"
libgfortran_version = "4.0.0"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "be101fcf010d3e8c8c2fe1d6484b167994f0bec0618dc656416e2fe359c143a5"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "b9d5f11c0bfb184d45a26e101bd58abac6e2a10d"
libgfortran_version = "5.0.0"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "af07814fbf862e9d1a0b281255c0d56b730212a01d5382e57cb46a030e5e579f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "bdc2e31cc78db3d36be674e78255c3c80118311e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "edddb4d8701825c079afe5305441a505473e02810f2782f2bfd25486b92940b3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "213598abd23dae9d2e117ba1d295bc0066a265e4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "6d5d2896e9b4ca977ff4ac5ccd4e56a9c11bcb37d708a35257bbd87dba01977f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "356532307ce835ac6aa2a99ef9129cab14b48c13"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "57fd3ff2c57585b120db2b181edd7cb56abab5d2433414e5379fbe3eb8f3f1b4"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "8b8041d916ded5c3dec48eefdea40b2d98414d4e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "a264fb7b8950ff488c696ee80d353da6f7d66d23b90333908b7b3206aa17eaf3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "fb06886d45f00c84eab4b3a83e1ce346156caec3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "08dc0a98fbbcdd2ac30c95d8f441784e7cf372190c56914a29487a7761f8168d"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "fb84e2fa40e5246ce92aa369591369dd7a9ff2c4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "0bcb056596437245486d43a8aedfa972ff8b5891949de629be53979744b0584a"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "d5a43ae31307f3dbf9981ea1560e8b4f08e882ec"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "cc9cadf4d1c6b14c0753480ec40aea8bcdb5b2e17f7507019dfce7140125fb0b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "bccddaf1f4c08a9a59da85779820d952f6d25911"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "77f93ff830c7444e287c407e2dac5a94d0239deec5c72457e68b51ebcb5b74c2"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "03baca225bf61e26a60c3f4d2c0e5934fc282b0a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "210e9d12fefe976b154fdde393c41fa783ef52c2f761a06330e486fa4bb40df6"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.0.0+0/QuantumEspresso.v7.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
