[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "41afd1d5f4043a9c7b55598f5b01e0559f4ef680"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "b4b6c27da7e02313005702e2a395ccf87c90d7b6f332ea7fce77ccd4d4e9c8fd"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "273d3312b2a70e6223250dbf4a39ab3f28b04104"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "93428e2fe1a67dc8fc8d762a1e4ef2f3c3b13083d5a304d316d7ef47225c9c32"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "37fab2cc83f29a2cd3022bf6eb88ab2d8a7abfc5"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "50cb9d15d0d5d80dbe021d8a0c354d9cf2a0e3930b6719d9ca17baba90511bf6"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "b7f522e4cd0d5fcd0388900518bb3b3c0ed07125"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3d7cf033c5e87239634d92c357048739735eb7e1159c1b1a06cf85ec0c94c592"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "566ba8d3f6f5bca0d44db7fdb40d509c521a4b7c"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "f13d5f2c4acc8f6459062c30e357b1f5185af5c4c86536d497088a6a69719417"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "90fb1f0fb0431af844f44873298421e952d29be6"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3e386177a85dd99e4fd11d51fa88312786273cf40bf661ac135f883e2db5733d"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "49be7dabe01c9763e311e483dd966f50cc7a4be3"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2ffd6d2167770923fc28f39439a657f0b074d7f4ff37de204d3a9002b3cdf729"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "259a051a28f8d47ce58010d2757435bd65526645"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "5279f820208796be5babb2546b3031e491139da14ec5f97c9f692927c2449522"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "e64ae83e2b550e08b4fd9788ee945fbccf7c1b45"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3afc155d27199dd2019c092c6f0a95debd65ec00c037a21f4315046bcbcc18df"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "4f8eb98397feeb52048edb18595cee8833c48950"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "6c22b4136387741d5474c87cec1c55f430c8ce9ba413b85744ac466e04bc13e3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "92441f30d4c8fe3917e8852cd067ee8c08fb2a92"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "e37ebc5bbe0d3b766343a720ca8e4b4235a83a3503bbcd1156497669aba5c11b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "5428829afb397d7336298968c119ece3452134f3"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "459e4623d3af3605535c8e63c0238cd9ea59612c67f5044475a3f2b6309710c1"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "a99aba81d4f62d3e12aaca688849aa0c4ca37b72"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "43dd9ff5f18c51e36e29b898b9c007ebd89d8b9460793daf37a0355fc94c99be"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.i686-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "b4e2d12db90e39a259ac606425e33d0e2c5e26bf"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "4fc2cc3d97da8c79ee8b72335287b5f90a3b7ee762e6d34a9255df2966f4f209"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.i686-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "2a6e99b2da0bbda4f2f0a5c701f8716fd0caee57"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2dc5361c374e2a93c58200327d387f3da77ed78a4f272b631f051617c28eeb74"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.i686-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "0e9476c46b5caef66435f9bf16323fe7ebd1e21b"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "28d84f582e575a51e11b0a2a8416c70901c7b9bba28be4de27f91c683b57bdb3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.i686-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "f91604cbd36417c78da93081a0c789494f08e547"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "fca158a625b3e4f6371ff45e9d4b9334106fcc23988fce7d43cc48ce657bb9f2"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.i686-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "060aabb57ac5e29477a40985611ea1ec94f480c5"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "cc17000cf3877d09a0c66ef93d82ced8f2bdb77732b083f157bf0baa78066fb0"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.i686-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "a2884c0a88177c09ec6c0a185770a3f95a2df2e8"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "32560bc956dd1c8d605af5ffdbc0e0a1f221f9ed33a96d7057e75b4a07f90f82"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "3044a0c4f081cfae2b425f1465a64d2a82f9f681"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "af7c1d82576d6fe96ca945f64522216699754aba1a5c20fd72a1ae98015b1f1f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "2f9f5a6b686a29231e31f1393956217a1fb4b6d3"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "8717ef4aec5f5e41affe7bf1913097fc5503f4fc73061859f88e6ea9cb97db14"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "eb1b1d99bacf935ab0214e65aa20d9e35f266430"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "7d4c950ea78a4ce71a5de0295a8fdced3a419c529c1eb513cb77bbcafe7328d5"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.riscv64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "383fbb0d3c2c4286ab3740713c30bfdcbe844673"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "4837f75fb03d8bebbd2fb5d36433ea691b46258b03df3ab83f39de12f22853c5"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.riscv64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "3c10f782768b4c82ce1093b3af2fd2794c26673e"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "fa343f439f1594f7cf2c2cf2992ccb3ac58ae745a30b6a0e8db9b3fd7946af7c"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.riscv64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "6327fbbd89d13ab76e8742dab9862e7a6eed51bd"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "010e01ceb100732a00b8f0c65b70ccb4e3deba7f3d7492d8d8170e4ee7c5f4e2"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "bb77ba1fc194a0b7eb711efc4ed983dd3a5a9f40"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "5e94166fe493a7f2071eed561b69af5279568f057cb04b66a91b2960477a859d"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "95dc7d81b9ae25b077b72b0ad8e9424c1cd31486"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "da794edf87ddd8ca4bffb50bbb110f2f38ecace14a464862049f99fa8297ea3c"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "9880df30b0c004abfe6631b3d90716d30ffeb3b4"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "f0d0ffcba93ded481adf30ebd5b93576c0cb681e86a7381222c1b82173f8b64a"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "5ca008eb686a396c7470f170eead2efd9003f3b0"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "8f458995bcdd72b5b3260ad3594311091166e50f2d4136d40f43ed3af3b1f6ef"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "4cdbe1625dff648bf051a716dd13e729338629e5"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "466540f22d5ceb5b37ba435580376624a1776cf81665e6137a1c26f3986ef69c"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "7069a5b5b3d453bad04beba09a3d8647b548e804"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "528eee07696cd77ade7d71afa49fe14bc9e8289df9bed01e862eeab6a05c6cb7"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "88c1921c84b6645fa23b77d8ee1902c41f87f686"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "c1444c76f33d360dcc96a23cb4ee7348f4122a18f8a063536f34fa94ee33823e"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "999886e150bffd688060b24bac8dd5a19bb761a4"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "65cff2437a9aa4130528d674d04b85e82c45dc189913f3a0a7dc64972a70fa1a"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "7b19db788144fbf4ac8e5ab4a6e7b8b2de2b81c9"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "e22068fc215fd4809140c753aa8c3b709c5ceeee19b4489c893c853bb1f8ca5a"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "aae4eaf66c7089af9a4112bdbb8a7c224d7728ea"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "ece1d47e5cb65146945a5558f110e5f33e370695b114212115cea856075200ad"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "9cd04e0d208635b03900769eaee66e59aa9eb4c8"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "b5c02a4653434c5bb00300d98546050e05cfed16f2132385c5f623d98b1e94ad"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.1+0/QuantumEspresso.v7.5.1.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
