[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "0264ac95d541607c96374e1dd76abb47d3bc6ad3"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "9c960e7538e4beb28c01b61d61774d9dda3dab45bb3464700e9e7eae59976a14"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "f48d113c99baf5f42b9bfcfa5687d48d97049bd7"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "bb13fdc3afde993facb8ee4e1bd9bb2e05f2fb32fb9534ad4d67961af256b1fd"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "5e7cc28245c72d3fd01f718c23913dbe8f8a50ad"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "bfd0b241c5fc63d6dd09d0112f1244c5b2ccbeefe3556fc14415fc0aef56997e"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "22c12f6e9c41fa60f0fab5f90062c0cb1281b3be"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "b4dfde69d1257d8d51dd2d60bf8b748b66e49a5f1ad4a464655595090baf7bfc"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "bd9054e7fa3700fb8b97aadfeaf55c96e2b4fde6"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "a39d772f51de806b35efd4eb16444375e8cac6f62351348273dfa54fcc6a7452"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "c28dc1451ba9e55d560e21029d3b53f9921ea948"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "fdd805346f575c81adc5f26ddf6f1c296a8ad542966cb31b57bd039c590ae179"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "68df4650e5f627c9c5d1a466343047754722402d"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "cfea3b39e625733ec7a565d80e87c3fc09e88d3735083ca13fda29355fd676fe"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "7c5f7552b7789cde8bc2a980b16c44d7ebdd7ee4"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "60e864991cea7864495df2f178a6b9265a7caba0e252d96c85b6e80ae7b1b029"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "6487043f196ef03756c48e0165eb4bbd68ef51dc"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "59fedaa1e8b659798df1bbb4572f3f762100f1e656a20bd3e94bfd70520875c3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "8ac1510035bdcfcd58d8d67a44fc1cfd59db0823"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "fb00028b12d0d70bba16fadb815c6d64d6906777e7125fd3656dff3bb0474f9b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "104ee783c3df0c444e31cece5f8b14178b12d188"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "6fd3a1c7f9946b19e39075692b7aba480ddae674792fa5e7ad7a29b844e8593e"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "3e53b383f1b0efe49e979acfa7a6beeaa9a074f5"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "f0b8aa3b2755338ce096812c498af3d4a307f4669dc9ddb930a056ff5b0e445b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "2addb9db5b00b1a3fe3534b28da7ac3c837bbb14"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "b1a594c9c534c0a320114379266b24a71b3848a4a6bc6f3d8f6947fdb8b88c50"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.i686-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "e079aac6a016fe525fec7b3d516e2d53069456a3"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2b2db0e1b3372863de10a16c31e2802df1d3fadc30e178c822923cafd5ef8ae8"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.i686-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "81ee0b9c13061dc6393387ced55df630f4c028c8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "f031883c86a80eb0a6cc8ea495867e70259919cff9d85b36c186f2a6c03e695f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.i686-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "0128c2807787da313a7005f709f15284a2418416"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "a72451593fe71cd02b41905bdbc44948bd7aa51b2dac883bca4f13ef21c1f8fc"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.i686-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "88f95f9899ad4387d5e8b08c207ec9d972f1d2f3"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "7ef55a7a7c16cbd9c89e262337793732b2718c8801266a5e9a0ec55b32112050"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.i686-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "3e14ee546be7d23707622b9429da6fd18efc4328"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "592aa59a4dad4fb1a79569ca9f591209d9c9ef550f64c2837309467326642ba7"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.i686-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "91f49b7f9badb03124998760782bbcfe89e61cdd"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "723aca5995502aabe0053b0361f16d7fc556f1a687020267b526c1a58d328231"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "bf4a36fc1c46add78db9272fd5c6c8342205a2ef"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "8fbc7d32330de13c80d3199e78f1334d18ff3bda104ecf4f284fd269c6d968ae"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "2e74391e9cb8e6a7e1c74c4d044426d8948d4284"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "5338ece5d7fd9c364885365167d68058952795454ae1a1f39d0ca746fe3b9e13"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "03192aaf143ab38191fb6f1ef67c7727a45fbdf9"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "15494d448d7e277fa5b7d97596c513dd69b6e97180e2071043a7680e9035d78f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.riscv64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "48734948488bef4ec57a8b72d6874dd663f5dcff"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "47bf5588e558b1a6339cceae6f565d046f07671a87e0dcbb367a54f5715a2e97"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.riscv64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "31f059929192daccb59aae2bae3f3e1bc4a822f5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "254bf3bb8f412fab814ba8652df69bacce2f7703f8eb59f71fd8a3749aeac791"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.riscv64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "dced6b0abf1235f2586ef3c616b31e503619eebe"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "d7a90454c8e99a813921b7848fc37c1992d5a6d756fe02a022b80eeb27812747"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "5a147f9d6c2ea0ec26cba397e3f45e4ddfe632f8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "5b1f5b934ec95edafd179d01219cb803ad666be96302612e9a9f3bfb6884dda0"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "ad5169335a0329c137cedac439b32df4ce0e6ce9"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "041e10975fe000de67a1245a51573640acab6e0d732cb4db89cf8f24bb216c9f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "66faccbf66d6d53e2aae4917dbe1fcee9a1029ae"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "d446730a35f7136ffe2a6a33638c5e524739666bd1d1c4133a6fa0d5d1d41c40"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "ea3da4384a32da7c6883842b84883f783a923f45"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "0cf14eeb64f8862d543fb4263508a2a647c86855ebf6aa5472f36e75152d71f0"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "cd39424bbdc55dd1b790a00cf55638d74d66f082"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2b24b08238d973f9120ca0c59bed7bf478081712dd32629ce40a493d56099596"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "bcd9c3206121923e7b456eee9b05cae7533c1957"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "821b9dc255e25417968ae1536d6fca6ff9bd69786c21c802cbce8e89292621a5"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "92755e901875c8103275adf8a40cee51472acd87"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "83ca6bcd4eac1072e0267905b4c35472ec1b71a0cfa2abcc57454795eb7679fe"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "372badb6dfa4ed023c4c479dde9dad2e40d44675"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "e114b8315b9efb03917808c69dc9ae746d1a11f50064c3b0316b2ddb97046ae2"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "17f6de77cd069beec1fd33fd7f0af246bffe65f6"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "0b9e3d5657c3d813a72e321930f91d6d9bd38b15ec30c4d0902821caffc816a1"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "aadb66a9e483d38fc0432234fc990e1f561a8087"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "055e955c44af12b8980bf42bb16f148c05f2f68df269390a660e3ef154c4a1d0"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "29a6f6f50f92be0fa7ae3d2f2706fce7d27cd9be"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "8378cb73a7acc89fed431da645ef68b21414cee7d6d4fc40ce94e81f54eabe67"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.4.1+2/QuantumEspresso.v7.4.1.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
