[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "407f6783fa83f2682b08adeb637f91e6854ffc12"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "76feae3dedcbafec727f13200ec46a64d4d0eb3e6c34f7a5f79ded173bdf0de5"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "c5ddb6f9d1159f73c3c4d948b15660421b00eda2"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "b31ffd0f9ff54eea7421cb7a0108bd14e09c56e7eef119276a329e19c36808f8"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "97b94608c271a99697539b60c1ed672428d17032"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "5a680a6ef9c946233cfabc4a04d8e9fd8dfab103bd9b1c2472adfb678d4b89c4"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "71115480ce6ccdda233e4a3d411f7e69d966c925"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2021b09f2e68ce99c928e01a912bc2d3e75ce13f8d9c98b1603165268cdc3ebc"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "54ba7e5b2caf87687ad9f29b730065cf3907785d"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "88313f8f8a3b6de396fa95af41084727b23bd32f91cd00fef0e266fd50790b9c"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "a72459fd295916862cffa8ec4c61dd04644df37c"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "0ff83fe70d8b99cfa1ff63301bdcf5da05a0ba7030edf01f12798d20e3a5a9c0"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "cf6dfcde0e15f2a0149353f587867767586fddf9"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "47f2f81ebc38251daa3af78eba1cc37f07352fc55c3e7d8fe78442dc9895c0aa"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "fe5e054adbefcb6ac936e446e0183292418e359b"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "69e6d48ed6216bcdc1df50f053b3ee0be116af4d6f81bb3f377656e9245fa8df"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "575355e00da10eec0a9f9ad930f6bc42007ef583"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "d3dc10bb4e5cce4bd9e5285dc901927ea2d3fa7e1fe404e6320cce14ee8561cf"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "59855f7b88e8c26dc2ac605c7d325f4ee641e1de"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "f8da19409da6880e4288d19d89faa8e37ba4c91d4f1aac93b0cfe5eb75f8ea5b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "bd5c757ec8c5b1fcf006981a19e5f416a66dea42"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "c7700d4867a9df6b9230f6405f9ee4fd06949dded19f39f287f67003afa66d74"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "9f3aeb917f79adba1f5aa02737416e8402eec635"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "85e9002aba7bf2d1668febb6c1216694ee0ba467cbbf3e5665ed6eedf3790f12"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "39ba6d3339abb1551405bd7a7acdb72497ebc28e"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "8d7d10355a214ac2175ed945669110a3013663051f716377a534203080627d21"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.i686-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "8956fe8c4a87fb999cbf3918aafb2a940229b3f7"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "0b651064f3f3121bd89bc7446f46a8621d5cbbfcc375fede01fbe7644bb29947"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.i686-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "96dea5b430203735af7211864de5a2ab421759e8"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "4113248afa9760103ef216d4ce72d4b273106f5b47a8666f9d78542d52d92251"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.i686-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "f4b7b2bed8da7a7806c6425ad0b63777cc5d764b"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "f043102782c9c1f68387c786cecce731e7aceb295c7eb2f5cb8e9bdd83de79dd"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.i686-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "22f974e87f4908140640f771ac69f5e611dce31b"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "f6e58edd6647b735e9e5aaf50140d9d87ea5d1fd6c08221461e32b8dc345ce38"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.i686-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "cf6860cc2cacd40bd79af4093df4ed6b73412ef6"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "af95d4377305925084df00b4e164784458ed18af16151cfb692b74fe540d2de9"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.i686-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "e2fc1dc527013035cd6fead57971d58481379b5e"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2e3dd33244ae79b70c09a439ca4f63f7fc27d8475c98091f572749ae7117da64"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "dd88a2653f7db16041999ee43a6489a32a321e6c"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "df6e99ea0bb3c47104bd72bf5df1413eb40763c0d85b26de74648a7a59f6e644"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "9e60b92f6cf159a0a507bbbe1ccbf7ae06bc18a1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "0d32a16df4a8c25bf9f61843740889d62c3af3ae59ba2da92ca27eb6163bcf20"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "992833a1c1b3018fed184d5a9cedcdf66d2ad09b"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "fc1709342a474ed2628ce8a537c521750f37cb07f9a4ed471c2c6f2392863930"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.riscv64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "54ec36b987733e7e19e6a7fa9ba628c1ec68a16d"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "95d9da96b8e9f878ca59a588df9df3747afec15467dd509f09a2ffe0cdbbbd9b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.riscv64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "riscv64"
git-tree-sha1 = "2e4132289ae1d4d8207a94fb75e38f1c45754846"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3920dffd23268ff2c7918c4823eb0dba5bc243d66f6630040624e5a7b64b429c"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.riscv64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "b606c0ec0687a8995825192f334133ff6fab0b99"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "c2721a94d16bd4353f773cfb841c9cfd070e5f4c127f0466399715bdac63e5ad"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "285e85f9fb0775d5449e04c1911046bc6275d367"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "0f6e569470643b3fba8a37aee6d2f97338ad8efd0e98636d93f15bfe93e87c29"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "c060a6f92d9053544d1a20500b59053dc597a2d1"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[QuantumEspresso.download]]
    sha256 = "d00701f0e68f78415b370ab6b04c0ff51bfbf59de7a43e2e9ebe6f52eb393fa4"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "c515868874b4c263dacd3859d35502bad9174991"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "aeed7a74a4259bb646c6b82a042d6f7bc8ee892329511d8edfe467817a3db13e"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "2eed934144115c98127c7b8407860cb47285b869"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "d0f4d727ff52775d4dc70f8277ae3c0b012172a326dabaa5abfbc5f6086eacd2"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "f1a41eac608cf1a4fb803effc6d86a62af7c8a80"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "e933f9ea2da6e7f54390aa1682c6031f7657798fd947565e773ed8c0da2a3d89"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "a2b2614e91a7294f6a8aa3b76b6c70cc8e43d090"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "12bcbda6a958affaaab142ce15779665aef7ee076548bf95ed0c9f0ad0cad686"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "ee9870597df8dcea9dcc2d6c55842ab2f28bb6fa"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "b082a43b52451138d418f3e564a74106c4978726c1396a42173a7bf7e37f8f4e"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "3b1dd55995fc7d2d2165bd40d4f79903f12fde65"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "f7d15dcabf5251fa812378153015717538aa6c02844430315878525a38965587"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "483fd5f74f04b46556d4a2aff644d0ad69b8bcc1"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "60edffdd5d06e8eec9515bd4922afa1c60afd97a3f58effd0d8c001205d7a6c1"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "b4e42679a49d6ba8e0684044d19efe08e43065bc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "26ec773f4af3e836f4164fbe2b65b948a163c392594eda79230bcaf7b6684877"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "d023caa6f03d3a6ee1c919682ddf286c75f11cfc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "21c2a8c177e1667acbb9161c846ce585e57a9e11487c624be5fd9226e4a566f3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v7.5.0+0/QuantumEspresso.v7.5.0.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
