[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "b1f77d0dc28640241eece9618ead7ba6b3ff5f2d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "469a3bcc3431f895ba4c45d85f0f79231701afb873c5e6a7f2d0c6c4a22a2ad1"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "fcf7a01aca4922508426a3b20aa82be0db2ea9ed"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "38b9c9a4ce1da06fe57f6c2e68b2c919e48e03f50be304df30d74ebf5c8bf9dd"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "64036fa930d6dd719acced4a92470cfe208733b2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "1fd95621f9c41632e049166c5456d091025028b81bd958c81fa954b069db9e67"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "4e126b88a64ea42e59939a132f605239862002ca"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "2c7ca94eb1c9deb851aca877b5f7cf6ce5253db069d603fc00e3aea4e0e80a67"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "485e96bc76ef94f303f3eeddbb7b60f0be95254d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "b59aca36a0d51e8e07af032214a5b8b847a2fbaac6ce83d27586de005c7ad145"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "aarch64"
git-tree-sha1 = "11bbe4f0a562100626805701130f5bd1478507f3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "22b52dc37a12fe837f9895679d891191ceabb0e6c8aabf5a0260cd09338fc70b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c22cb6455589a0e734c51e2b3217eea7f90fc423"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "cf7c8012962c6bc3992e623f7de9bc7e94a35c9962c180080066646968e7219c"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a28e528c5bfb6b1228c8b75c9262af4720ff1aa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "b7432340f50abb820f5c1a810e272f007d7c8fa1a0a9c79dc35a18cba4f8b1f1"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2d9f81b070bca01e8c1c7118d36b5e68624db638"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "e48841b7b1171ef07fcc08118f71ca82fc2fb325d321587a884822b01bf10373"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18f070893f2efa585763b989ca8e339cb73045cd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "854db205b2197a82a1d406b994750ef43efb8c3a7eebb15cefeff1e3866aaa00"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af224ce2e64bab40d4b46d3e347b3e30467a9870"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "e942db27bf06b996a81454a4f1b589b703bfd1a7389e9dbe972eb446c7f1e3b1"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "89ab9e35bdf1c257ff37f1565c79b1f34c96e3a2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "23cda21f8866953070b8445bc6b47599ea73e8ca8d5268793cff2721f8bf43f8"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "003dead4b44e147bc5b25322d376996d49ca6dcd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "aaceee9c563b75ac579e21b5201e54ac60b991102766d58d8f943453261c8414"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.i686-linux-gnu-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "b1718dcba6cdd09831b385417e431e0f8bd7a717"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "5be85fe74ab3b1bf7219b01ae59afd24d1e566caa14cf5daa71d5717472ff2a1"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.i686-linux-gnu-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "dfe13777c5d867b47565eb8884ba706544e56deb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "603f1bca55d9b9cbb6b1eb7e248b593f2449d72d498395162fcfea74ddd00542"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.i686-linux-gnu-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "3c43f53a34b5ff04e9c9be9fe547727a1f14213e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3deb64ac855e22964002607e60166ad4b6b0f5a7ab5576492a36100bf050f335"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.i686-linux-musl-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "c3a1c9ced9e7efe88b772282e8ff43f6a26285b1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3b3e268380dd5d893bb48e6c1d89d557391a0bf3851a3eb6d0021ed073bb2f0f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.i686-linux-musl-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "i686"
git-tree-sha1 = "0a1de4f9f64b035055ce15ee05c434715763fb36"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "4678636286d552c5e6b9848f3beeb12a0ee586fe42172401f6ff58b578e6f30f"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.i686-linux-musl-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "0734c215c4f53d9876c36b3e16e3d1e46d0edee8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "b90851da0561e34905878c086b6eccf3edef4679c65e2797afe8d7ec4d3fa3fa"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "7d24c564c4004b43a0b4f20f6e574d78fc87518e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "47ed71f271c569c5e9243f58b67f40e5991d27cc1d41958232e167104cc3bf7d"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "powerpc64le"
git-tree-sha1 = "adfb059e6bb264761dbc151ecb9990c24b71cbd4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "3f7d7e0de79ace146d69f10ec2673835d08ed44e87b17d66de22edc5cbba39cb"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "c286ad0f0ed3aa66215bad2f17951f3dd59e0e81"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "18a7f3a03767fedd386325d47745ca5ec6b6e286740d448bbfaa04db58829ebe"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "c3375c4006f7ee5e2507aea85778849335e60521"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "fe7bba29dfa196cc6fb1b4f2ca2311c86113ea0e34f40e3a5e4e7ee41aace8e6"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "2cfd67b8326337893b9338a88bae3114f8ebebbb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "cb1fe3209e25208de3c370a266e59689fff775f89131c0eb2d4626cdceab8bf3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "791e7458150f8ce4e9f14f6d67e65eeb17a8910c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "978cd3dc6f00676b7fc8bfe570a814541ae1804e6ac69cd1d96b7fe732064631"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "8a6a7eb8156e98f4d891d0badcf38d9c92593c3d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "26172750ac9e20d4af9ca92df93f3beff33cfa59befcba58245ea5b503bc9513"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "27dfe6b002e77321e9d05e2b6a210e0dc28fd326"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[QuantumEspresso.download]]
    sha256 = "78d63e848d0c1e2b8d6e471d74b66419c14607e4dd6192887e63b6b8b389421b"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "f248e632aa56bc9de9a70f54115556b85a794f93"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "d0cc4b28205ca1b46623fa20fbf6ddf4199b3612fa55b3e7a574ecef09f183af"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "00c43413846d315eb537db163ce56b6bf0a66949"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "1c3cdda1dc6eb98e8bde1477573b5f6b2452511147fb74a48e26b727a0d581c3"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[QuantumEspresso]]
arch = "x86_64"
git-tree-sha1 = "e947413125d758a0746ee91aa8a4c617e43bc291"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[QuantumEspresso.download]]
    sha256 = "e5c9a11af3a18cd19d1fdd5e56d8bd31aeafa823b54900c00998a7d735f5a2b8"
    url = "https://github.com/JuliaBinaryWrappers/QuantumEspresso_jll.jl/releases/download/QuantumEspresso-v6.7.0+1/QuantumEspresso.v6.7.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
